"""rename department

Revision ID: 3390a0bcb99d
Revises: ded6db505295
Create Date: 2025-09-17 08:02:28.557107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3390a0bcb99d'
down_revision = 'ded6db505295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
